-- Example Queries

-- 1 Tracking Transactions Back to Customers
SELECT c.Customer_ID, c.First_Name, c.Last_Name, t.Trans_ID, t.Date, t.Total_Cost
FROM CUSTOMER c
JOIN VEHICLE v ON c.Customer_ID = v.Customer_ID
JOIN `TRANSACTION` t ON v.License_Plate = t.License_Plate
ORDER BY c.Customer_ID, t.Date;



-- 2 Breakdown of Different Customer Cars
SELECT v.Make, v.Model, COUNT(*) AS Vehicle_Count
FROM VEHICLE v
GROUP BY v.Make, v.Model
ORDER BY Vehicle_Count DESC;



-- 3 Services Bought by Customers
SELECT s.Wash_Type, COUNT(ts.Service_ID) AS Times_Bought
FROM TRANSACTION_SERVICE ts
JOIN SERVICE s ON ts.Service_ID = s.Service_ID
GROUP BY s.Wash_Type
ORDER BY Times_Bought DESC;



-- 4 Number of Customers by Number of Vehicles
SELECT Vehicle_Count, COUNT(*) AS Number_of_Customers
FROM (
    SELECT c.Customer_ID, COUNT(v.License_Plate) AS Vehicle_Count
    FROM CUSTOMER c
    JOIN VEHICLE v ON c.Customer_ID = v.Customer_ID
    GROUP BY c.Customer_ID
) AS subquery
GROUP BY Vehicle_Count
ORDER BY Vehicle_Count DESC;



-- 5 Revenue Generated per Service Type
SELECT s.Wash_Type, SUM(s.Price) AS Revenue
FROM `TRANSACTION` t
JOIN TRANSACTION_SERVICE ts ON t.Trans_ID = ts.Trans_ID
JOIN SERVICE s ON ts.Service_ID = s.Service_ID
GROUP BY s.Wash_Type
ORDER BY Revenue DESC;



-- 6 Average Number of Services per Transaction
SELECT AVG(Service_Count) AS Average_Services
FROM (
    SELECT COUNT(ts.Service_ID) AS Service_Count
    FROM TRANSACTION_SERVICE ts
    GROUP BY ts.Trans_ID
) AS subquery;



-- 7 Distribution of Transaction Dates
SELECT DATE(t.Date) AS Transaction_Date, COUNT(*) AS Transactions_Count
FROM `TRANSACTION` t
GROUP BY Transaction_Date
ORDER BY Transactions_Count DESC;



-- 8 Top 5 Employees by Number of Transactions Handled
SELECT e.Emp_ID, e.Name, COUNT(t.Trans_ID) AS Transactions_Handled
FROM EMPLOYEE e
JOIN `TRANSACTION` t ON e.Emp_ID = t.Emp_ID
GROUP BY e.Emp_ID, e.Name
ORDER BY Transactions_Handled DESC
LIMIT 5;



-- 9 Breakdown of Additional Services
SELECT s.Wash_Type, COUNT(ts.Service_ID) AS Service_Count
FROM SERVICE s
JOIN TRANSACTION_SERVICE ts ON s.Service_ID = ts.Service_ID
WHERE s.Wash_Type NOT IN ('Basic Wash', 'Deluxe Wash', 'Full Service')
GROUP BY s.Wash_Type
ORDER BY Service_Count DESC;



-- 10 Overview of customers and their overall services
SELECT 
    c.Customer_ID,
    c.First_Name,
    c.Last_Name,
    v.License_Plate,
    v.Make,
    v.Model,
    v.Year,
    v.Color,
    rs.Service_ID
FROM
    RECEIVES_SERVICE rs
JOIN VEHICLE v ON rs.License_Plate = v.License_Plate
JOIN CUSTOMER c ON v.Customer_ID = c.Customer_ID
ORDER BY c.Customer_ID, v.License_Plate, rs.Service_ID;



-- 11 Total Revenue Generated by Each Customer
SELECT 
    c.Customer_ID, 
    c.First_Name, 
    c.Last_Name, 
    SUM(t.Total_Cost) AS Total_Revenue
FROM CUSTOMER c
JOIN VEHICLE v ON c.Customer_ID = v.Customer_ID
JOIN `TRANSACTION` t ON v.License_Plate = t.License_Plate
GROUP BY c.Customer_ID, c.First_Name, c.Last_Name
ORDER BY Total_Revenue DESC;



-- 12 Number of Services per Vehicle
SELECT 
    v.License_Plate, 
    v.Make, 
    v.Model, 
    COUNT(rs.Service_ID) AS Number_of_Services
FROM RECEIVES_SERVICE rs
JOIN VEHICLE v ON rs.License_Plate = v.License_Plate
GROUP BY v.License_Plate, v.Make, v.Model
ORDER BY Number_of_Services DESC;


-- 13 Most Popular Service by Year
SELECT 
    YEAR(t.Date) AS Year, 
    s.Wash_Type, 
    COUNT(ts.Service_ID) AS Times_Bought
FROM `TRANSACTION` t
JOIN TRANSACTION_SERVICE ts ON t.Trans_ID = ts.Trans_ID
JOIN SERVICE s ON ts.Service_ID = s.Service_ID
GROUP BY YEAR(t.Date), s.Wash_Type
ORDER BY Year, Times_Bought DESC;


-- 14 Customer Loyalty: Repeat Customers
SELECT 
    c.Customer_ID, 
    c.First_Name, 
    c.Last_Name, 
    COUNT(DISTINCT t.Trans_ID) AS Number_of_Transactions
FROM CUSTOMER c
JOIN VEHICLE v ON c.Customer_ID = v.Customer_ID
JOIN `TRANSACTION` t ON v.License_Plate = t.License_Plate
GROUP BY c.Customer_ID, c.First_Name, c.Last_Name
HAVING COUNT(DISTINCT t.Trans_ID) > 1
ORDER BY Number_of_Transactions DESC;


-- 15 Monthly Revenue Breakdown
SELECT 
    YEAR(t.Date) AS Year, 
    MONTH(t.Date) AS Month, 
    SUM(t.Total_Cost) AS Monthly_Revenue
FROM `TRANSACTION` t
GROUP BY YEAR(t.Date), MONTH(t.Date)
ORDER BY Year, Month;

-- 16 Customers Who Have Not Used Services Recently
SELECT Customer_ID
FROM CUSTOMER
WHERE Customer_ID NOT IN (
    SELECT DISTINCT Customer_ID
    FROM VEHICLE
    JOIN RECEIVES_SERVICE ON VEHICLE.License_Plate = RECEIVES_SERVICE.License_Plate
    JOIN TRANSACTION ON TRANSACTION.Trans_ID = RECEIVES_SERVICE.Service_ID
    WHERE Date > DATE_SUB(CURDATE(), INTERVAL 6 MONTH)
);

-- 17 Revenue Generated by Each Employee
SELECT Emp_ID, SUM(Total_Cost) AS Total_Revenue
FROM TRANSACTION
GROUP BY Emp_ID
ORDER BY Total_Revenue DESC;

-- 18 Store with the Highest Revenue
SELECT Store_No, SUM(Total_Cost) AS Total_Revenue
FROM TRANSACTION
GROUP BY Store_No
ORDER BY Total_Revenue DESC
LIMIT 1;